name: Despliegue

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Instalar Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Instalar Surge
      run: npm install -g surge

    - name: Desplegar a Surge
      run: surge ./ superficial-governor.surge.sh --token ${{ secrets.SURGE_TOKEN }}

